# Generated by Django 4.2.1 on 2023-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='flavors',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='flavors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
