# Generated by Django 4.2.1 on 2023-05-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('food_app', '0002_remove_fooditem_flavors_delete_flavor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditeminventory',
            name='truck_owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
    ]
