# Generated by Django 4.2.1 on 2023-05-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('food_app', '0003_fooditeminventory_truck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditeminventory',
            name='truck_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
    ]
